-- FitQuest — Migrazione v2.1
-- Aggiunge nuovi achievement SENZA toccare i dati esistenti.
-- Sicura da rieseguire più volte (INSERT OR IGNORE).

INSERT OR IGNORE INTO achievements (key, name, description, icon, xp_reward, rarity) VALUES
  ('five_workouts','Apprendista','Completa 5 workout','🗡️',75,'common'),
  ('twentyfive_workouts','Veterano','Completa 25 workout','⚒️',300,'epic'),
  ('hundred_workouts','Centurione','Completa 100 workout','🏛️',1000,'legendary'),
  ('level_15','Campione','Raggiungi il Livello 15','🌟',600,'epic'),
  ('level_30','Semidio','Raggiungi il Livello 30','☀️',2500,'legendary'),
  ('xp_1000','Primo Tesoro','Accumula 1.000 XP totali','💰',100,'common'),
  ('xp_10000','Tesoro del Drago','Accumula 10.000 XP totali','🐉',800,'epic'),
  ('streak_3days','Scintilla','Allenati 3 giorni di fila','✨',100,'common'),
  ('streak_7days','Fiamma Eterna','Allenati 7 giorni di fila','🔥',400,'epic'),
  ('streak_14days','Inarrestabile','Allenati 14 giorni di fila','🌋',1000,'legendary'),
  ('month_12','Costanza d''Acciaio','12 allenamenti in 30 giorni','⚙️',350,'rare'),
  ('weekend_warrior','Guerriero del Weekend','Allenati di sabato o domenica','🎉',60,'common'),
  ('early_bird','Alba di Ferro','Allenati tra le 4 e le 7 del mattino','🌅',100,'rare'),
  ('night_owl','Gufo Notturno','Allenati dopo le 21 o di notte','🦉',100,'rare'),
  ('marathon','Maratoneta','Sessione da almeno 90 minuti','⏳',200,'rare'),
  ('hours_10','Dieci Ore','10 ore totali di allenamento','🕰️',250,'rare'),
  ('hours_50','Cinquanta Ore','50 ore totali di allenamento','⌛',900,'epic'),
  ('big_session','Quest Epica','6 o più esercizi in un solo workout','📚',120,'common'),
  ('variety_10','Sperimentatore','Prova 10 esercizi diversi','🧪',120,'common'),
  ('variety_25','Enciclopedia','Prova 25 esercizi diversi','📖',400,'epic'),
  ('all_rounder','Completo','Allena 6 gruppi muscolari diversi','🎯',250,'rare'),
  ('sets_100','Cento Serie','Completa 100 serie totali','💯',200,'rare'),
  ('sets_500','Cinquecento Serie','Completa 500 serie totali','🔱',700,'epic'),
  ('heavy_100','Club dei 100','Solleva 100 kg o più in una serie','🏋️',300,'rare'),
  ('calisthenics_master','Maestro del Corpo Libero','Registra Planche, Front/Back Lever, Human Flag o Muscle-Up','🤸',500,'legendary'),
  ('first_routine','Stratega','Crea la tua prima routine','📋',60,'common'),
  ('first_program','Pianificatore','Crea il tuo primo programma','🗺️',80,'common'),
  ('custom_exercise','Inventore','Aggiungi un esercizio personalizzato','✏️',60,'common'),
  ('favorites_5','Collezionista','Salva 5 esercizi tra i preferiti','⭐',60,'common'),
  ('measurements_30','Diario Corporeo','Registra 30 misurazioni','📔',500,'epic');
